### PR TITLE
Create resto11.py

### PR DESCRIPTION
**Pull request by thepieterdc**
Never programmed a single line of python before; was more of a test.
This modification stores fish/vegetarian seperately from meat; for whatever the purpose might be.

### CODE REVIEW

**Comment by JensTimmerman** [comment]
Hi, Why did you create a new scraper module for this? It is kind of hard to see what changes you made, and why don't the changes fit in the original scrapper.py ?

The point of version control is that you can just make changes to a file and previous versions of that file will be saved. So there is no need to manually version your files.
see e.g., https://guides.github.com/introduction/flow/ for more information on how to use github.

So can you please rename that file to scrapper.py so people can easily locate the changes you made, and no history is lost.

**Comment by thepieterdc** [comment]
@JensTimmerman wouldn't that break the existing apps that make use of the api?

**Comment by JensTimmerman** [comment]
Well it's hard to tell, because it's hard to see what exactly changed, 
it will only break existing applications  if your changes aren't backwards compatible and the new changes are deployed.

If you don't want to break existing applications you could extend the current class with a new class inside the current module, and in your application use the new class, and let the old applications use the old one?

**Comment by NoctuaNivalis** [comment]
@thepieterdc: oh, that's not a problem. Even if you change the file, as long as we don't merge and deploy it, the API is safe. We'll of course only merge and deploy it when it's well tested. As @JensTimmerman said, it's easier for us to check the code if it's inline with the current code.

**Comment by JensTimmerman** [comment]
@thepieterdc For future reference: There is no need to close a PR and create a new one, you can just push new changes to the same branch you used as source for your PR and the PR will be updated with the new changes.

**Pull request closed without merging**
