### PR TITLE
Resto Menu 2.0

### PR DESCRIPTION
**Pull request by feliciaan**
Rewrite of resto menu in swift, using collection view instead of scrollview.
New resto menu

### CODE REVIEW

**Comment by Silox** [comment]
I really like the header; it's minimalistic and clear. The rest however seems not very polished: there is a lot of empty space and the layout seems like there hasn't been a put a lot of thought into it. Perhaps it appears more full if a realistic menu is used (2x groenten, and 3 main courses).  As there is a lot of space, I'm wondering why we still shorten things such as the Veg. dish and the price of the wokschotel. I think more margin at the borders and perhaps a thin line under a caption to polish it up a bit.

**Comment by feliciaan** [comment]
@Silox: it's empty because of the reason you said, and also because the screenshot is taken from an iPhone 6, with an iPhone 4S (which we still support) the content would barely fit in the screen.

An other issue is that since the previously week the API has changed, see #202.

**Comment by Silox** [comment]
Is it possible to create screenshots with a fuller menu and also on a 4S? That way we could judge the space usage better.

**Comment by feliciaan** [comment]
simulator screen shot 15 aug 2015 11 11 09
On the 4S it's too big, you've to scroll in it.

**Pull request merged**
