### PR TITLE
(Previous pull; scraper11.py->scraper.py)

### PR DESCRIPTION
**Pull request by thepieterdc**
Modified resto scraper to include fish & vegetarian meals seperate from meat meals, might be useful in the future. Example for week 43: https://gist.github.com/thepieterdc/fb573fa49148c056ec57

2 commits were git cli tests

### CODE REVIEW

**Comment by JensTimmerman** [comment]
Hi pieter, 

Could you keep the original `def write_1_0(menus):` function's output the same and add a new function
`def write_1_1(menus):`
which splits the `fish` and `vegetarion` of.
and writes to
`OUTFILE_1_1 = "resto/1.1/menu/{}/{}.json"`

then add a call to this function in the main function.

This way old clients can keep on using their normal json files, and new clients can start using the new api with the fish and vegetarian options split off.

**Comment by thepieterdc** [comment]
@JensTimmerman there you go ;)

**Comment by JensTimmerman** [comment]
@thepieterdc I believe it would be nicer if you could keep just 1 `get_day_menu` but use it's output as input to the 2 different write_x_y functions.

**Comment by thepieterdc** [comment]
@JensTimmerman something like this? (excuse me for bad python; I only have Java courses)

**Comment by feliciaan** [comment]
We incorporated or take on these changes in the new resto scraper.

**Pull request closed without merging**
